version: "3"
services:
  k6:
    container_name: k6
    environment:
      K6_OUT: influxdb=http://k6-influxdb:8086/k6
    extra_hosts:
      - host.docker.internal=host-gateway
    image: grafana/k6:latest
    ports:
      - "6565:6565"
    volumes:
      - ./scripts:/scripts

  k6-grafana:
    container_name: k6-grafana
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      GF_AUTH_BASIC_ENABLED: "false"
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: "/var/lib/grafana/dashboards/k6-load-testing-results_rev3.json"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    image: grafana/grafana:10.2.4
    ports:
      - "3000:3000"
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    depends_on:
      - k6-influxdb

  k6-influxdb:
    container_name: k6-influxdb
    image: influxdb:1.8
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb

volumes:
  influxdb-data:
